# Generated by Django 2.1.7 on 2019-02-24 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_rechnungstermine',
            name='company_ID',
        ),
        migrations.AddField(
            model_name='t_rechnungstermine',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data.t_firmen', verbose_name='t_firmen'),
        ),
    ]
