# Generated by Django 2.1.7 on 2019-03-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190226_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_rechnungstermine',
            name='status',
            field=models.IntegerField(default=0, max_length=11, verbose_name='status'),
        ),
    ]
